# Generated by Django 5.0.6 on 2024-06-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_version_version_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=20),
        ),
    ]
