# Generated by Django 5.0.6 on 2024-07-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_publish_product', 'Can publish product')]},
        ),
    ]
